# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AvailabilityBundle\Entity\Availability:
    type: entity
    table: availability
    repositoryClass: WellCommerce\Bundle\AvailabilityBundle\Repository\AvailabilityRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
