well_commerce_availability:
    configuration:
        availability:
            orm:
                factory: WellCommerce\Bundle\AvailabilityBundle\Factory\AvailabilityFactory
                repository: WellCommerce\Bundle\AvailabilityBundle\Repository\AvailabilityRepository
                mapping: "@WellCommerceAvailabilityBundle/Resources/config/doctrine/Availability.orm.yml"
                entity: WellCommerce\Bundle\AvailabilityBundle\Entity\Availability
            api:
                exposed: true
                dataset: availability.dataset.admin
                manager: availability.manager
        availability_translation:
            orm:
                mapping: "@WellCommerceAvailabilityBundle/Resources/config/doctrine/AvailabilityTranslation.orm.yml"
                entity: WellCommerce\Bundle\AvailabilityBundle\Entity\AvailabilityTranslation


