WellCommerce\Bundle\AvailabilityBundle\Entity\Availability:
    fields:
        id:
            groups:
                - default
                - availability
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        createdBy:
            groups:
                - availability
        updatedBy:
            groups:
                - availability
        deletedBy:
            groups:
                - availability
        translations:
            groups:
                - availability
    callbacks: {  }
